spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/hainan?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
hainan:
  wano: 1058921020
  csno: 1058921020